using System;
using System.Collections.Generic;
using System.Linq;
using C7GameData;
using Serilog;

namespace C7Engine {
	// Civ3's culture flipping: a city may defect to a neighbouring civ whose
	// culture outweighs its owner's ("cultural reversion").
	//
	// Each interturn, every city may flip with the chance
	//
	//   P = [(F + T) * Cc * H * (Cte / Cty) - G] / D
	//
	// from the Flip Calc thread
	// (https://forums.civfanatics.com/threads/flip-calc-calculates-the-probability-of-culture-flips.53157/,
	// also https://forums.civfanatics.com/threads/babylon-ii-civ3-culture-flip-calc.53181/
	// and Fitz's https://apolyton.net/forum/miscellaneous/archives/civ3-general-archive/63497-culture-flip-formula),
	// built on Firaxis' (Dan Magaha's) description of the rule in
	// https://forums.civfanatics.com/threads/culture-flipping-exposed.14337/:
	//  - F: "the number of foreign nationals in the city in question
	//    (resisters are counted twice)".
	//  - T: "the number of the 21-tile city-radius squares of the city in
	//    question that fall inside your [the other civ's] cultural borders".
	//  - Cc: 2 if the other civ has more culture in the city than its owner,
	//    else 1: "each city has a 'memory' and remembers the total amount of
	//    culture generated by any civ who has ever occupied it ... if the
	//    'attacking' civ has more historical culture in the city than the
	//    'defender', the chance of that city flipping to the attacker are
	//    doubled" (City.perPlayerCulture).
	//  - H: 2 in civil disorder ("Civil Disorder in a city doubles the chance
	//    of that city flipping"), 1/2 celebrating ("We Love the King...Day in
	//    a city halves the chance"), else 1.
	//  - Cte / Cty: the other civ's total culture over the owner's.
	//  - G: "the number of land-based combat units (e.g., any unit with at
	//    least 1 point of offensive and defensive capability) in the city in
	//    question are subtracted": the owner's land units with attack >= 1
	//    and defence >= 1, so defenceless or attackless units (workers,
	//    catapults) don't count. Air units don't count (alexman,
	//    https://codehappy.net/apolyton/threads/51715-4.htm); since patch
	//    1.17f "it is now possible to completely suppress a city's cultural
	//    reversion with enough military units"
	//    (https://forums.civfanatics.com/threads/patch-v1-17f-readme-is-here.16272/).
	//  - D = 2000 * d, d being the ratio of the city's distances to the two
	//    capitals, "capped between 0.25 and 4", with distance
	//    "max(x,y) + 0.5*min(x,y)" (Flip Calc v1.5): "if you're closer to
	//    your capital than the other city is to its capital, you've got a
	//    better chance of getting a flip" (Magaha).
	//
	// "A newly-captured town will _never_ flip on the first interturn"
	// (https://forums.civfanatics.com/threads/culture-flips.661194/). When a
	// city flips, "All the city defenders die. The 'capturing' civ gets one
	// free defender in the city", and units outside the city are kept
	// (https://forums.civfanatics.com/threads/cultural-conversion-question.87425/;
	// "All units that are in the city are lost",
	// https://forums.civfanatics.com/threads/armies-captured-in-culture-flips.90904/).
	//
	// Disputed or unsourced, and our choices:
	//  - Distance: Magaha later wrote in the thread "I would assume this is
	//    measured in tiles, based on the pathfinding algorithm's
	//    determination of the shortest path from the city in question to the
	//    civ's capital city". As that is hedged ("I would assume"), and the
	//    calculators, fitted to observed flips, use the straight-line
	//    distance above, so do we (UNVERIFIED; a path can also be undefined,
	//    e.g. to a capital overseas).
	//  - Each city's memory (City.perPlayerCulture) is the culture the city
	//    made while each civ owned it: a turn's culture is added to its owner
	//    at the time, the totals are kept when the city changes hands, and
	//    they are saved (SaveCity.perPlayerCulture).
	//  - UNVERIFIED: which civ a city flips to when several could take it.
	//    Each civ's chance is worked out and the city may flip only to the
	//    one with the best chance, with a single roll.
	//  - UNVERIFIED: F counts every citizen not of the owner's nationality,
	//    whichever civ they come from, as the calculators do.
	//  - UNVERIFIED: a civ with no capital is taken to be as far as can be
	//    from the city (d capped). Capitals aren't immune: no Civ3 source
	//    says they are, but a capital's own distance of 0 caps d at 4, so
	//    D = 8000 and they rarely flip.
	//  - UNVERIFIED: the free defender is the best defensive land unit the
	//    new owner can build in the city.
	//  - UNVERIFIED: the city otherwise changes hands as when incited to
	//    revolt (CityInteractions.TransferCity): it keeps its citizens and
	//    buildings, except the palace and small wonders, and doesn't resist.
	//  - UNVERIFIED: flips happen at war or at peace alike, with no
	//    diplomatic penalty; no source says otherwise.
	//  - UNVERIFIED: courthouses play no part; only forum anecdotes say so.
	//  - The BIQ's CULT section (propaganda and resistance chances) plays no
	//    part in flips in any source found.
	public static class CultureFlip {
		private static readonly ILogger log = Log.ForContext(typeof(CultureFlip));

		// D = DistanceFactor * d.
		public const double DistanceFactor = 2000;
		public const double MinDistanceRatio = 0.25;
		public const double MaxDistanceRatio = 4;

		// The chance a city flips to a civ this interturn, and why.
		public class Chance {
			public Player to;
			public int foreigners;
			public int tiles;
			public int memoryFactor;
			public double moodFactor;
			public double cultureRatio;
			public int garrison;
			public double distanceRatio;
			public double probability;
		}

		// Rolls for every city that may flip; called once per round, after
		// every player has played (the "interturn").
		public static void ProcessEndOfRound(GameData gameData) {
			if (gameData.rules?.AllowCultureFlips == false) {
				return;
			}
			foreach (City city in gameData.cities.ToList()) {
				Chance chance = BestChance(gameData, city);
				if (chance == null || chance.probability <= 0) {
					continue;
				}
				if (GameData.rng.NextDouble() < chance.probability) {
					Flip(gameData, city, chance.to);
				}
			}
		}

		// The civ the city is likeliest to flip to this interturn, with the
		// chance, or null if it can't flip.
		public static Chance BestChance(GameData gameData, City city) {
			Player owner = city.owner;
			if (owner == null || owner.isBarbarians || owner.defeated || city.ownerChangedTurn == gameData.turn) {
				return null;
			}
			Chance best = null;
			foreach (Player other in gameData.players) {
				if (other == owner || other.isBarbarians || other.defeated || other.cities.Count == 0) {
					continue;
				}
				Chance chance = ChanceOfFlippingTo(gameData, city, other);
				if (chance.probability > 0 && (best == null || chance.probability > best.probability)) {
					best = chance;
				}
			}
			return best;
		}

		// The chance, from 0 to 1, that the city flips to the other civ this
		// interturn, by the formula above.
		public static Chance ChanceOfFlippingTo(GameData gameData, City city, Player other) {
			Player owner = city.owner;
			Chance chance = new() { to = other };

			int resistersFrom = city.residents.Count - Math.Clamp(city.resisters, 0, city.residents.Count);
			for (int i = 0; i < city.residents.Count; ++i) {
				Civilization nationality = city.residents[i].nationality;
				if (nationality != null && nationality != owner.civilization) {
					// Resisters, the last ones in residents, count twice.
					chance.foreigners += i >= resistersFrom ? 2 : 1;
				}
			}

			int radius = Math.Max(1, gameData.rules?.MaxRankOfWorkableTiles ?? 2);
			foreach (Tile t in city.location.GetTilesWithinRankDistance(radius)) {
				if (t != city.location && t.OwningPlayer() == other) {
					++chance.tiles;
				}
			}

			chance.memoryFactor = city.GetCultureFor(other) > city.GetCultureFor(owner) ? 2 : 1;
			chance.moodFactor = city.isInCivilDisorder ? 2 : city.celebrating ? 0.5 : 1;
			chance.cultureRatio = (double)CultureReport.TotalCulture(other) / Math.Max(1, CultureReport.TotalCulture(owner));
			chance.garrison = Garrison(city);
			chance.distanceRatio = DistanceRatio(city, owner, other);

			double influence = (chance.foreigners + chance.tiles) * chance.memoryFactor * chance.moodFactor * chance.cultureRatio;
			chance.probability = Math.Clamp((influence - chance.garrison) / (DistanceFactor * chance.distanceRatio), 0, 1);
			return chance;
		}

		// The owner's land combat units in the city: those with at least 1
		// attack and 1 defence (Magaha, above). Every unit in an army counts,
		// and the army too, though it has no strength of its own, so long as
		// it holds a unit that can fight: "all individual units within an
		// army count, including the actual army unit" (alexman, above).
		public static int Garrison(City city) {
			return city.location.unitsOnTile.Count(u => u.owner == city.owner && u.IsLandUnit() && CountsAsGarrison(u));
		}

		private static bool CountsAsGarrison(MapUnit unit) {
			if (unit.IsArmy()) {
				return unit.IsCombatUnit();
			}
			return unit.unitType.attack >= 1 && unit.unitType.defense >= 1;
		}

		// d: the other civ's capital's distance from the city over the
		// owner's, capped.
		public static double DistanceRatio(City city, Player owner, Player other) {
			double ours = DistanceToCapital(city, owner);
			double theirs = DistanceToCapital(city, other);
			double ratio;
			if (ours <= 0) {
				ratio = theirs <= 0 ? 1 : MaxDistanceRatio;
			} else {
				ratio = theirs / ours;
			}
			return Math.Clamp(ratio, MinDistanceRatio, MaxDistanceRatio);
		}

		// "max(x,y) + 0.5*min(x,y)" tiles from the city to the civ's capital,
		// or infinity if it has none.
		public static double DistanceToCapital(City city, Player player) {
			City capital = player.cities.Find(c => c.IsCapital());
			if (capital == null) {
				return double.PositiveInfinity;
			}
			GameMap map = city.location.map;
			// Each step along one of the map's two diagonal axes changes
			// both coordinates by one.
			int dx = Math.Abs(map.CalculateXDelta(capital.location.XCoordinate, city.location.XCoordinate));
			int dy = Math.Abs(map.CalculateYDelta(capital.location.YCoordinate, city.location.YCoordinate));
			double a = (dx + dy) / 2.0;
			double b = Math.Abs(dx - dy) / 2.0;
			return Math.Max(a, b) + 0.5 * Math.Min(a, b);
		}

		// Hands the city to the civ whose culture won it over.
		public static void Flip(GameData gameData, City city, Player to) {
			Player from = city.owner;
			Tile tile = city.location;
			log.Information("{City} has flipped from {From} to {To}", city, from, to);

			// "All units that are in the city are lost."
			foreach (MapUnit unit in tile.unitsOnTile.ToList()) {
				if (unit.owner != to && unit.hitPointsRemaining > 0 && tile.unitsOnTile.Contains(unit)) {
					gameData.RemoveUnit(unit);
				}
			}

			// UNVERIFIED: as when a capital is captured, its spaceship is lost.
			if (city.capital) {
				SpaceRace.DestroySpaceship(from, to);
			}

			CityInteractions.TransferCity(city, to);

			// "The 'capturing' civ gets one free defender in the city."
			UnitPrototype defender = city.ListProductionOptions(gameData).OfType<UnitPrototype>()
				.Where(u => u.IsLandUnit() && u.defense > 0)
				.MaxBy(u => u.defense);
			if (defender != null) {
				city.AddUnit(defender, gameData);
			}

			// Both sides hear of it; a spectator watching every civ hears it
			// once.
			NewsEvent news = new();
			if (from.IsToldNews) {
				new MsgShowDomesticAdvisorPopup(from, $"The people of {city.name}, drawn by the culture of the {to.civilization.noun}, have defected to them!") { newsEvent = news }.send();
			}
			if (to.IsToldNews) {
				new MsgShowDomesticAdvisorPopup(to, $"Drawn by our culture, the people of {city.name} have left the {from.civilization.noun} and joined us!") { newsEvent = news }.send();
			}
		}
	}
}
