"""Gunpowder and modern foot soldiers, and the industrial/modern settlers and
workers (archetypes in models/foot_modern.py).

'Settler Industrial Ages' and 'Worker Industrial Ages' have no art of their
own: their INIs point at the Modern Times flics (..\\Settler Modern
Times\\...), so the Modern Times sheets serve both (the game resolves the
'..' in the path).

`shots` lists the frames where the original shows a muzzle flash.
"""

_FIRE = {'ATTACK1': 'fire'}

UNITS = {
    'Musketman': {
        'archetype': 'soldier',
        'colors': {'skin': '#d09a74', 'hair': '#3a2a1c', 'helmet': '#a4a4aa', 'vest': '#6e6253', 'belt': '#3a2d2a',
                   'strap': '#3a2d2a', 'stockings': '#a09a90', 'boots': '#26201c', 'bottles': '#d8d1c9',
                   'stock': '#5e3e24', 'garter': '#2e2e30', 'plume': '#d8d4cc'},
        'tint': ['top', 'trousers'],
        'desat': 0.4,
        'hair': 'short', 'hat': 'morion', 'plume': True, 'top': 'long_sleeved', 'vest': 'jerkin',
        'straps': ['bandolier'], 'legs': 'breeches', 'feet': 'shoes',
        'gun': 'matchlock', 'offhand': 'musket_rest', 'hold': 'shoulder', 'aim': 'rest',
        'fire_start': 'aim', 'fire_end': 'aim', 'flash': 'musket', 'smoke': 'heavy', 'flash_size': 0.34,
        'shots': {'ATTACK1': [5, 6, 7]},
        'fortify': 'aim', 'victory': 'raise',
        'actions': dict(_FIRE),
    },
    'Musketeer': {
        'archetype': 'soldier',
        'colors': {'skin': '#c88a68', 'hair': '#2a1e16', 'hat': '#4a2a2b', 'top': '#7d4742', 'coat': '#7d4742',
                   'belt': '#292622', 'trousers': '#292622', 'boots': '#161311', 'stock': '#5a3a24', 'strap': '#3a2a20',
                   'steel': '#c3bfbb'},
        'tint': ['vest', 'plume'],
        'hair': 'long', 'hat': 'cavalier', 'plume': True, 'top': 'long_sleeved', 'coat': 0.40, 'vest': 'jerkin',
        'straps': ['crossbelt'], 'legs': 'trousers', 'feet': 'tall_boots',
        'vest_skirt': 0.0, 'gun': 'musket', 'hold': 'port', 'aim': 'shoulder', 'fire_start': 'aim', 'fire_end': 'carry',
        'poses': {'carry': {'hand_r': (0.22, 0.18, 0.98), 'w_main': (-12, -24, 0)}},
        'flash': 'musket', 'smoke': 'heavy', 'shots': {'ATTACK1': [6, 7]},
        'fortify': 'guard', 'victory': 'hat',
        'actions': dict(_FIRE),
    },
    'Rifleman': {
        'archetype': 'soldier',
        'colors': {'skin': '#d0a07a', 'hair': '#2a1e16', 'trousers': '#6a7a88', 'boots': '#141210',
                   'belt': '#2a1e14', 'strap': '#2a1e14', 'visor': '#141210', 'stock': '#8a5a32',
                   'steel': '#b8bcc2'},
        'tint': ['top', 'hat'],
        'hair': 'short', 'hat': 'kepi', 'top': 'long_sleeved', 'straps': ['crossbelt', 'crossbelt_l'],
        'legs': 'trousers', 'feet': 'shoes',
        'gun': 'rifle_bayonet', 'hold': 'port', 'aim': 'shoulder', 'fire_start': 'guard', 'fire_end': 'guard',
        'flash': 'burst', 'smoke': 'heavy', 'shots': {'ATTACK1': [7]},
        'fortify': 'guard', 'victory': 'hat',
        'actions': dict(_FIRE),
    },
    'Guerilla': {
        'archetype': 'soldier',
        'colors': {'skin': '#b88e6c', 'hair': '#201811', 'top': '#46601a', 'trousers': '#46601a',
                   'boots': '#3a2a18', 'belt': '#2a2014', 'stock': '#6a4917'},
        'camo': {'top': ['#6c8a22', '#25340a', '#5a4a24'], 'trousers': ['#6c8a22', '#25340a', '#5a4a24']},
        'tint': ['hat', 'strap'],
        'hair': 'short', 'hat': 'bandana', 'top': 'sleeved', 'straps': ['crossbelt', 'crossbelt_l'],
        'legs': 'trousers', 'feet': 'boots',
        'poses': {'carry': {'hand_r': (0.34, 0.14, 1.12)}},
        'gun': 'ak', 'hold': 'vertical', 'aim': 'hip', 'fire_start': 'aim',
        'flash': 'burst', 'smoke': 'light', 'flash_size': 0.26,
        'shots': {'ATTACK1': [0, 1, 2, 7, 8, 9, 11, 12, 13], 'VICTORY': [4, 5, 8, 9]},
        'fortify': 'guard', 'victory': 'fire_air',
        'actions': {'ATTACK1': 'fire', 'ATTACK2': 'lunge'},
    },
    'Infantry': {
        'archetype': 'soldier',
        'colors': {'skin': '#d0a27a', 'hair': '#3a2a1c', 'helmet': '#6c6c66', 'trousers': '#8a7a5e',
                   'gaiters': '#cabca7', 'boots': '#5a3a22', 'strap': '#a08a62', 'belt': '#a08a62',
                   'pack': '#7a7058', 'pouch': '#8e8064', 'stock': '#7a5230'},
        'camo': {'trousers': ['#6a5a3a', '#a4967c']},
        'tint': ['top'],
        'desat': 0.8,
        'hair': 'short', 'hat': 'm1', 'top': 'sleeved', 'straps': ['webbing', 'crossbelt'], 'pack': 'field',
        'legs': 'trousers', 'gaiters': True, 'feet': 'shoes',
        'gun': 'garand', 'hold': 'hip', 'aim': 'shoulder', 'fire_start': 'aim',
        'flash': 'burst', 'smoke': 'light', 'shots': {'ATTACK1': [0, 1, 2]},
        'fortify': 'guard', 'victory': 'raise',
        'actions': dict(_FIRE),
    },
    'Marine': {
        'archetype': 'soldier',
        'colors': {'skin': '#c8a07a', 'hair': '#2a2018', 'helmet': '#5a6448', 'vest': '#5e6950',
                   'trousers': '#55604a', 'boots': '#141414', 'belt': '#2a2a24', 'strap': '#2a2a24'},
        'camo': {'vest': ['#353e35', '#909369', '#55352d'], 'trousers': ['#353e35', '#909369', '#55352d']},
        'tint': ['top', 'hatband'],
        'hair': 'short', 'hat': 'pasgt', 'hatband': True, 'top': 'long_sleeved', 'vest': 'flak',
        'legs': 'trousers', 'cargo': True, 'feet': 'boots',
        'gun': 'm16', 'hold': 'low', 'aim': 'hip', 'fire_start': 'aim', 'fire_end': 'aim',
        'flash': 'burst', 'smoke': None, 'flash_size': 0.22, 'shots': {'ATTACK1': [1, 3, 5, 7, 9, 11, 13]},
        'fortify': 'aim', 'victory': 'raise',
        'actions': dict(_FIRE),
    },
    'Paratrooper': {
        'archetype': 'soldier',
        'colors': {'skin': '#c8a07a', 'hair': '#2a2018', 'helmet': '#d8d8dc', 'top': '#9a979c',
                   'trousers': '#9a979c', 'boots': '#202022', 'belt': '#3a3a3e', 'strap': '#3a3a3e',
                   'pack': '#78787e', 'canopy': '#ececea'},
        'camo': {'top': ['#d4d2d2', '#5a5a62', '#eeede8'], 'trousers': ['#d4d2d2', '#5a5a62', '#eeede8']},
        'tint': ['vest'],
        'hair': 'short', 'hat': 'para', 'top': 'long_sleeved', 'vest': 'flak', 'pack': 'para',
        'legs': 'trousers', 'cargo': True, 'feet': 'boots',
        'gun': 'carbine', 'hold': 'across', 'aim': 'shoulder', 'fire_start': 'aim', 'fire_end': 'aim',
        'flash': 'burst', 'smoke': None, 'flash_size': 0.18, 'shots': {'ATTACK1': [0, 1, 5, 9, 13]},
        'fortify': 'aim', 'victory': 'fist',
        'actions': {'ATTACK1': 'fire', 'BUILD': 'drop'},
    },
    'WWII Paratrooper': {
        'archetype': 'soldier',
        'colors': {'skin': '#c89c74', 'hair': '#2a2018', 'helmet': '#545342', 'helmet_net': '#7e7c5c',
                   'top': '#737257', 'trousers': '#737257', 'boots': '#6a4426', 'belt': '#38362c',
                   'strap': '#38362c', 'pack': '#545342', 'stock': '#7e5c30', 'canopy': '#e4dfcc', 'kneeband': '#4a4636'},
        'camo': {'top': ['#9e9562', '#49432f', '#2e2a20'], 'trousers': ['#9e9562', '#49432f', '#2e2a20']},
        'tint': ['vest'],
        'hair': 'short', 'hat': 'm1', 'net': True, 'top': 'long_sleeved', 'vest': 'flak', 'kneebands': True,
        'flag_patch': True, 'straps': ['harness', 'webbing', 'crossbelt', 'crossbelt_l'], 'pack': 'para',
        'legs': 'trousers', 'cargo': True, 'feet': 'boots',
        'gun': 'thompson', 'hold': 'across', 'aim': 'hip', 'fire_start': 'aim', 'fire_end': 'aim',
        'flash': 'burst', 'smoke': None, 'flash_size': 0.22, 'shots': {'ATTACK1': [1, 3, 5, 7, 9, 11, 13]},
        'fortify': 'aim', 'victory': 'fist',
        'actions': {'ATTACK1': 'fire', 'BUILD': 'drop'},
    },
    'TOW Infantry': {
        'archetype': 'tow_team',
        'desat': 0.75,
        'scale': 0.82,
        'soldier': {
            'colors': {'skin': '#c89c74', 'hair': '#2a2018', 'helmet': '#525a40', 'trousers': '#4e5638',
                       'boots': '#4a3420', 'belt': '#2e2e26', 'olive': '#5c6046', 'top': '#5c6046'},
            'camo': {'trousers': ['#2f3326', '#7a7a5a', '#523d25']},
            'tint': ['strap'],
            'hair': 'short', 'hat': 'pasgt', 'top': 'long_sleeved', 'flag_patch': True, 'straps': ['harness'],
            'legs': 'trousers', 'cargo': True, 'feet': 'boots',
        },
    },
    'Settler Modern Times': {
        'archetype': 'soldier',
        'colors': {'skin': '#c89a74', 'hair': '#413025', 'top': '#d6cdbc', 'trousers': '#a19379', 'hat': '#9a8a66',
                   'boots': '#251c17', 'belt': '#413025', 'pack': '#6a4a2e', 'bedroll': '#4a3a2a',
                   'strap': '#3a2a1c', 'wood': '#5a3a22'},
        'tint': ['vest'],
        'hair': 'short', 'hat': 'boonie', 'top': 'long_sleeved', 'vest': 'jerkin', 'legs': 'trousers',
        'feet': 'boots', 'pack': 'hiker', 'straps': ['crossbelt', 'crossbelt_l'], 'vest_skirt': 0.0,
        'weapon': 'staff',
    },
    'Worker Modern Times': {
        'archetype': 'soldier',
        'colors': {'skin': '#c8966a', 'hair': '#5a3a22', 'trousers': '#7a6648', 'boots': '#2b221e',
                   'belt': '#3a2c20', 'strap': '#5a4630', 'sack': '#e8e8e0'},
        'tint': ['top'],
        'desat': 0.8,
        'hair': 'short', 'top': 'tunic', 'vest': 'bib', 'bib_back': True, 'straps': ['braces', 'crossbelt'], 'build': 'lean', 'legs': 'trousers',
        'feet': 'boots',
        'weapon': 'shovel',
        'work_tools': {'work_hammer': 'trowel'},
        'actions': {'CAPTURE': 'captured'},
        'stance': {'hand_r': (0.26, 0.20, 0.86), 'hand_l': (-0.22, 0.24, 0.88), 'w_main': (-92, 0, 88),
                   'root_pos': (0, 0, -0.03), 'spine': (-6, 0, 0), 'head': (6, 0, 0),
                   'elbow_l': (-0.6, -0.8, -0.2)},
    },
}
