"""Ancient and medieval foot soldiers and specialists (the 'footman' archetype,
models/foot_ancient.py, a humanoid with more gear).

Not here: Ansar Warrior (mounted). 'warrior' (lowercase) is the same folder
as 'Warrior' (catalog/ancient.py) on a case-insensitive file system.
"""
from models.foot_ancient import dir_euler
from catalog.ancient import BOW_AIM

# Weapons held low with both hands, head down to the right (berserk's axe)
_AXE_LOW = dir_euler((0.40, 0.30, -0.86))

# Shield bearers run with the shield kept up in front
_SHIELD_RUN = {'hand_l': (-0.22, 0.34, 1.05), 'elbow_l': (-0.8, -0.5, -0.3)}
# A spear carried level at the hip, point forward
_SPEAR_LEVEL = {'hand_r': (0.30, 0.04, 1.02), 'w_main': (-92, 0, 2), 'elbow_r': (0.8, -0.6, -0.2)}
# A spear raised overhand behind the shield, the point forward and a little down
_SPEAR_OVERHAND = {'hand_r': (0.30, -0.02, 1.48), 'w_main': (-100, 0, 4), 'elbow_r': (0.9, -0.3, 0.3),
                   'hand_l': (-0.20, 0.40, 1.08)}

UNITS = {
    'Hoplite': {
        'archetype': 'footman',
        'colors': {'skin': '#c88a50', 'hair': '#3a2616', 'helmet': '#c8963e', 'cuirass': '#c0903c',
                   'boots': '#b8883a', 'pteruges': '#8a6436', 'belt': '#5a3a20', 'shield_face': '#d0a048',
                   'shield_emblem': '#8a3a2a', 'wood': '#5a3a20', 'top': '#c8bca0'},
        'tint': ['crest', 'shield_rim'],
        'metal': ['helmet', 'cuirass', 'boots'],
        'desat': 0.85,
        'build': 'muscular',
        'hair': 'none', 'top': 'sleeved', 'cuirass': True, 'bottom': 'skirt', 'wraps': 'greaves',
        'gear': ['corinthian', ('pteruges', {'length': 0.17})],
        'weapon': 'spear', 'offhand': 'shield_round',
        'props': {'shield_round': ('aspis', {}), 'spear': ('spear_long', {})},
        'actions': {'ATTACK1': 'attack_thrust', 'ATTACK2': 'attack_thrust'},
        'overrides': {'RUN': dict(_SHIELD_RUN, **_SPEAR_LEVEL), 'FORTIFY': _SPEAR_OVERHAND}, 'shield_front': ['RUN'],
    },
    'Legionary': {
        'archetype': 'footman',
        'colors': {'skin': '#d0985c', 'hair': '#2e2018', 'helmet': '#a8a8b0', 'bottom': '#7a2622', 'top': '#7a2e28', 'belt': '#4a3020',
                   'boots': '#4a3424', 'plate': '#b4b4bc', 'collar': '#e8e4dc', 'shield_rim': '#9a9aa0',
                   'shield_emblem': '#d8d4c8', 'pteruges': '#5a3a22'},
        'tint': ['crest', 'shield_face'],
        'metal': ['helmet', 'shield_rim'],
        'desat': 0.45,
        'build': 'muscular',
        'hair': 'short', 'top': 'sleeved', 'bottom': 'skirt', 'wraps': 'boots',
        'gear': ['galea', 'segmentata', 'collar', ('pteruges', {'length': 0.16, 'n': 8})],
        'weapon': 'sword', 'offhand': 'shield_oval',
        'props': {'sword': ('gladius', {}), 'shield_oval': ('scutum', {})},
        'actions': {'ATTACK1': 'attack_thrust', 'ATTACK2': 'attack_thrust'},
        'overrides': {'RUN': _SHIELD_RUN}, 'shield_front': ['RUN'],
    },
    'Immortals': {
        'archetype': 'footman',
        'colors': {'skin': '#b07a4c', 'hair': '#1e1612', 'cuirass': '#a88a58', 'bottom': '#a88a58',
                   'belt': '#5a4028', 'boots': '#d8b040', 'cap_cloth': '#ece8da', 'stripe': '#d0b070'},
        'tint': ['top'],
        'metal': [],
        'desat': 0.85,
        'build': 'muscular',
        'hair': 'short', 'beard': True, 'top': 'long_sleeved', 'cuirass': True, 'bottom': 'skirt', 'wraps': 'boots',
        'gear': ['tiara', ('sleeves', {'color': '#9a8660'}), ('chest_strap', {'color': '#5a4028'}), ('trousers', {'baggy': 1.18, 'tint': False, 'color': '#9a8660', 'stripes': 'stripe'})],
        'weapon': 'sword', 'props': {'sword': ('scimitar', {})},
        'actions': {'ATTACK1': 'attack_chop', 'ATTACK2': 'attack_slash'},
    },
    'Impi': {
        'archetype': 'footman',
        'colors': {'skin': '#5e3c26', 'hair': '#140e0a', 'bottom': '#4a3424', 'belt': '#3a2a1c', 'headband': '#2a1e14',
                   'wood': '#6a4a2c'},
        'tint': ['feather', 'tufts', 'armband'],
        'metal': [],
        'desat': 0.5,
        'build': 'brawny',
        'hair': 'short', 'top': 'bare', 'bottom': 'loincloth',
        'gear': ['feather_crown', 'tufts', ('bands', {'where': ('arm',)})],
        'weapon': 'spear', 'offhand': 'shield_oval',
        'props': {'spear': ('iklwa', {}), 'shield_oval': ('cowhide', {})},
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Jaguar Warrior': {
        'archetype': 'footman',
        'colors': {'skin': '#8a5634', 'hair': '#1a1210', 'belt': '#e0a838', 'gold': '#e0a838', 'wood': '#6a4a2a',
                   'jaguar': '#c87436', 'jaguar_spot': '#2a1810',
                   'armband': '#c89a40', 'anklet': '#c89a40', 'pectoral': '#b89048'},
        'tint': ['bottom', 'feather', 'shield_face'],
        'metal': [],
        'desat': 0.85,
        'build': 'muscular',
        'hair': 'none', 'top': 'bare', 'bottom': 'loincloth', 'sandals': False,
        'gear': ['jaguar', 'pectoral', ('bands', {'where': ('wrist', 'arm')}),
                 ('bands', {'mat': 'anklet', 'where': ('knee', 'ankle')}),
                 ('bands', {'mat': 'gold', 'color': '#e0a838', 'tint': False, 'where': ('forearm',), 'r': 0.058})],
        'weapon': 'club', 'offhand': 'shield_round',
        'props': {'club': ('macuahuitl', {'length': 0.62}), 'shield_round': ('chimalli', {})},
        'actions': {'ATTACK1': 'attack_chop', 'ATTACK2': 'attack_lunge'},
    },
    'Javelin Thrower': {
        'archetype': 'footman',
        'colors': {'skin': '#8a5a3a', 'hair': '#1a1210', 'belt': '#e0b030', 'gold': '#e8b830', 'wood': '#6a4a2a',
                   'armband': '#c8a040'},
        'tint': ['bottom', 'feather', 'flap', 'pectoral'],
        'metal': [],
        'desat': 0.68,
        'build': 'muscular',
        'hair': 'short', 'top': 'bare', 'bottom': 'loincloth',
        'gear': ['feather_headdress', 'pectoral', ('loin_flap', {'length': 0.34}), ('bands', {'where': ('arm', 'knee', 'ankle')}),
                 ('bands', {'mat': 'gold', 'color': '#e8b830', 'tint': False, 'where': ('wrist',)})],
        'weapon': 'spear', 'offhand': 'javelins',
        'props': {'spear': ('javelin', {}), 'javelins': ('javelin_bundle', {})},
        'stance': {'hand_l': (-0.36, 0.10, 0.92), 'w_off': (-6, 0, 0)},
        'actions': {'ATTACK1': 'attack_throw'},
        # (the planted javelins keep the measured height up: the fall is early)
        'events': {'DEATH': {'down': 0.22}},
    },
    'Libyan Mercenary': {
        'archetype': 'footman',
        'colors': {'skin': '#a07250', 'hair': '#1e1612', 'helmet': '#b8a068', 'cuirass': '#a2a2a6',
                   'bottom': '#e2dfd0', 'belt': '#4a4030', 'boots': '#6a5a44', 'shield_face': '#e6e2d8',
                   'shield_rim': '#b09868', 'wood': '#5e4a34'},
        'tint': ['top', 'shield_emblem'],
        'metal': ['helmet', 'cuirass', 'shield_rim'],
        'desat': 0.45,
        'hair': 'short', 'beard': True, 'top': 'tunic', 'cuirass': True, 'bottom': 'skirt', 'wraps': 'greaves',
        'gear': ['attic', ('sleeves', {'color': '#dcd8cc', 'forearm': False})],
        'weapon': 'spear', 'offhand': 'shield_round',
        'props': {'shield_round': ('round_painted', {}), 'spear': ('spear_long', {})},
        'actions': {'ATTACK1': 'attack_thrust', 'ATTACK2': 'attack_thrust'},
    },
    'Berserk': {
        'archetype': 'footman',
        'colors': {'skin': '#c8946a', 'hair': '#d0b050', 'helmet': '#8e8e96', 'fur': '#5a4028', 'belt': '#3a2a1a',
                   'bracers': '#4e3a26', 'top': '#6a5e50',
                   'boots': '#5a4028', 'wood': '#8a6a40'},
        'tint': ['trousers'],
        'desat': 0.9,
        'build': 'brawny',
        'hair': 'none', 'top': 'sleeved', 'bottom': 'skirt', 'wraps': 'boots', 'bracers': True,
        'gear': ['conical', 'braids', 'fur_vest', ('trousers', {'tint': True, 'baggy': 1.08})],
        'weapon': 'axe', 'props': {'axe': ('battle_axe', {'scale': 1.35})},
        'twohand': 0.44,
        'stance': {'hand_r': (0.30, 0.26, 0.82), 'w_main': _AXE_LOW},
        'actions': {'ATTACK1': 'attack_chop', 'ATTACK2': 'attack_lunge'},
        'events': {'ATTACK1': {'reach_max': 0.78}, 'ATTACK2': {'reach_max': 0.7}},
    },
    'Enkidu Warrior': {
        'archetype': 'footman',
        'colors': {'skin': '#b07448', 'hair': '#1a1410', 'pelt': '#6e5a44', 'belt': '#4a3424', 'wood': '#6a3e24',
                   'fringe': '#a08a68'},
        'tint': ['bottom', 'bracers', 'headband'],
        'metal': [],
        'build': 'brawny',
        'hair': 'long', 'top': 'bare', 'bottom': 'kilt', 'bracers': True, 'back': 'pelt',
        'gear': [('long_beard', {'length': 0.30, 'width': 0.10}), 'streamers', ('fur_cape', {'mat': 'pelt'}), ('pteruges', {'mat': 'fringe', 'n': 16, 'length': 0.08, 'z0': -0.24})],
        'weapon': 'spear', 'props': {'spear': ('spear_long', {})},
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Gallic Swordsman': {
        'archetype': 'footman',
        'colors': {'skin': '#e0a878', 'hair': '#d07a30', 'belt': '#4a3020', 'boots': '#6a4428', 'checks': '#1a1a2e',
                   'shield_face': '#a87848', 'shield_rim': '#8a8a90', 'bronze': '#b0b0b8'},
        'tint': ['trousers', 'armband'],
        'metal': ['shield_rim'],
        'build': 'brawny',
        'hair': 'none', 'top': 'bare', 'bottom': 'loincloth', 'wraps': 'boots',
        'gear': ['spiky', ('trousers', {'tint': True, 'baggy': 1.06, 'checks': 'checks'}),
                 ('bands', {'where': ('arm', 'wrist')})],
        'weapon': 'sword', 'offhand': 'shield_round',
        'props': {'sword': ('long_sword', {})},
        'actions': {'ATTACK1': 'attack_lunge', 'ATTACK2': 'attack_chop'},
    },
    'Bowman': {
        'archetype': 'footman',
        'colors': {'skin': '#d09a62', 'hair': '#2a1c12', 'cuirass': '#7a5a30', 'helmet': '#6a4c30', 'belt': '#3a2a18', 'wraps': '#6a4a2c',
                   'wraps_band': '#3e2616', 'gold': '#e0b840', 'leather': '#5a3a20'},
        'tint': ['top', 'bottom'],
        'metal': [],
        'desat': 0.85,
        'build': 'muscular',
        'hair': 'short', 'beard': True, 'helmet': 'cap', 'top': 'sleeved', 'bottom': 'skirt',
        'wraps': 'wraps', 'gear': [('vest', {'mat': 'cuirass'}), ('cap_knob', {})],
        'weapon': None, 'offhand': 'bow', 'back': 'quiver',
        'offhand_mesh': ('bold_bow', {'height': 1.3}),
        'stance': {'hand_l': (-0.18, 0.34, 1.02), 'w_off': (-62, 0, -60), 'elbow_l': (-0.6, -0.8, -0.2)},
        'overrides': {'FORTIFY': BOW_AIM},
        'actions': {'ATTACK1': 'attack_shoot'},
    },
    'Longbowman': {
        'archetype': 'footman',
        'colors': {'skin': '#d8b08c', 'hair': '#8a6a40', 'helmet': '#d0c8a8', 'sleeve': '#9a9488', 'trousers': '#8e887c',
                   'bottom': '#6e6656',
                   'belt': '#1e1a16', 'boots': '#1e1a18', 'leather': '#6a5030', 'wood': '#6a4a28'},
        'tint': ['top', 'plume'],
        'metal': [],
        # a pale cloth hood (chaperon) with a civ-colored feather, not hair
        'hair': 'short', 'helmet': 'hood', 'top': 'tunic', 'bottom': 'kilt', 'wraps': 'boots',
        'gear': [('sleeves', {'color': '#9a9488'}), ('trousers', {'baggy': 0.85}),
                 ('plume', {'base': (0.09, -0.02, 0.22), 'tip': (0.13, -0.12, 0.05), 'n': 3, 'r0': 0.03,
                            'spread': 0.02})],
        'weapon': None, 'offhand': 'bow', 'offhand_mesh': ('longbow', {}), 'back': 'quiver',
        'stance': {'hand_l': (-0.30, 0.20, 1.0), 'w_off': (0, 0, 0), 'elbow_l': (-0.7, -0.6, -0.3)},
        'overrides': {'FORTIFY': BOW_AIM},
        'actions': {'ATTACK1': 'attack_shoot'},
    },
    'Medieval Infantry': {
        'archetype': 'footman',
        'colors': {'skin': '#d8a07a', 'hair': '#3a2a1c', 'mail': '#84848c', 'helmet': '#b4b4bc', 'belt': '#4a3420',
                   'boots': '#c8c8cc', 'shield_face': '#a88a5c', 'wood': '#6a4a2a', 'bottom': '#84848c'},
        'tint': ['top'],
        'metal': ['helmet', 'mail', 'boots', 'bottom'],
        'hair': 'none', 'top': 'tunic', 'bottom': 'kilt', 'wraps': 'boots',
        'gear': ['coif', ('sleeves', {'mat': 'mail', 'color': '#84848c', 'finish': 'metal'}),
                 ('trousers', {'mat': 'mail', 'baggy': 0.9})],
        'weapon': 'club', 'offhand': 'shield_round',
        'props': {'club': ('flail', {}), 'shield_round': ('wooden_round', {})},
        'actions': {'ATTACK1': 'attack_chop', 'ATTACK2': 'attack_slash'},
    },
    'Pikeman': {
        'archetype': 'footman',
        'colors': {'skin': '#d8a07a', 'hair': '#3a2a1c', 'helmet': '#a8a8b0', 'cuirass': '#b0b0b8', 'plate': '#9c9ca4',
                   'trousers': '#8a8682', 'bottom': '#8a8682', 'belt': '#3a2a1a', 'boots': '#6a4a2c',
                   'wood': '#6a4a2a', 'top': '#8c8a86'},
        'tint': ['sleeve', 'emblem'],
        'metal': ['helmet', 'cuirass'],
        'desat': 0.8,
        # a steel breastplate with a civ-colored cross, civ-colored puffed upper sleeves
        'hair': 'short', 'beard': True, 'top': 'long_sleeved', 'cuirass': True, 'bottom': 'skirt', 'wraps': 'boots',
        'gear': [('kettle', {'brim': 0.04, 'comb': True}), 'tassets', ('trousers', {'baggy': 0.95}),
                 ('sleeves', {'tint': True, 'forearm': False, 'puffy': 1.08}),
                 ('cross', {'mat': 'emblem', 'z': 0.15, 'big': 1.35})],
        'weapon': 'spear', 'props': {'spear': ('pike', {'length': 2.9, 'grip': 1.0})},
        'twohand': 0.5, 'twohand_actions': ['ATTACK1', 'FORTIFY'],
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Samurai': {
        'archetype': 'footman',
        'colors': {'skin': '#e0b080', 'hair': '#141214', 'trousers': '#4a4868', 'bottom': '#4a4868', 'belt': '#1e1c2a',
                   'sandal': '#ecece8',
                   'collar': '#ecebe6'},
        'tint': ['top'],
        'metal': [],
        'desat': 0.6,
        'hair': 'none', 'top': 'long_sleeved', 'bottom': 'skirt', 'sandals': True,
        'gear': ['topknot', 'collar', ('sleeves', {'color': '#3e3e52', 'wide': 1.7}), 'katana_hip',
                 ('trousers', {'baggy': 1.25})],
        'weapon': 'sword', 'props': {'sword': ('katana', {'size': 1.4})},
        'twohand': 0.17, 'twohand_actions': ['ATTACK1', 'ATTACK2', 'FORTIFY'],
        'sheathed': ['DEFAULT', 'RUN', 'FIDGET'],
        'actions': {'DEFAULT': 'idle_crossed', 'ATTACK1': 'attack_chop', 'ATTACK2': 'attack_slash'},
    },
    'Swiss Mercenary': {
        'archetype': 'footman',
        'colors': {'skin': '#d8a07a', 'hair': '#4a3a2c', 'helmet': '#c8c8d0', 'trousers': '#9a3428', 'stripe': '#1a1210',
                   'sleeve': '#ecebe8', 'belt': '#2a1e18', 'boots': '#1a1414', 'cuirass': '#c0c0c8',
                   'bottom': '#9a3428'},
        'tint': ['top', 'plume', 'shaft'],
        'metal': ['helmet', 'cuirass'],
        'desat': 0.65,
        'hair': 'short', 'beard': True, 'top': 'tunic', 'bottom': 'skirt', 'wraps': 'boots',
        'gear': [('kettle', {'brim': 0.03}), ('plume', {'base': (0.0, 0.0, 0.26), 'tip': (0.0, -0.18, 0.40), 'n': 4,
                                                         'r0': 0.05, 'spread': 0.06}),
                 ('sleeves', {'puffy': 1.4}), ('trousers', {'baggy': 1.15, 'stripes': 'stripe'}),
                 ('chest_strap', {'color': '#3a2a20'})],
        'weapon': 'spear', 'props': {'spear': ('pike', {'length': 2.9, 'grip': 1.0, 'halberd': False, 'shaft': 'shaft'})},
        'twohand': 0.5, 'twohand_actions': ['ATTACK1', 'FORTIFY'],
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Ninja': {
        'archetype': 'footman',
        'colors': {'skin': '#d0a07a', 'hood': '#2a3020', 'top': '#2c3222', 'trousers': '#262c1e', 'bottom': '#2c3222', 'boots': '#161a12'},
        'tint': ['belt'],
        'metal': [],
        'hair': 'none', 'top': 'long_sleeved', 'bottom': 'skirt', 'wraps': 'boots',
        'gear': ['ninja_hood', ('trousers', {'baggy': 1.05}), 'sash_ends'],
        'weapon': 'sword', 'offhand': 'kama_l',
        'props': {'sword': ('kama', {'size': 1.4}), 'kama_l': ('kama', {'size': 1.4})},
        'stance': {'w_off': (-140, 0, 20)},
        'actions': {'ATTACK1': 'attack_lunge', 'ATTACK2': 'attack_slash'},
    },
    'Explorer': {
        'archetype': 'footman',
        'colors': {'skin': '#d8a07a', 'hair': '#3a2a1c', 'helmet': '#b4b4bc', 'cuirass': '#c4c4cc', 'trousers': '#55526a',
                   'bottom': '#55526a', 'boots': '#a8a8ac', 'belt': '#3a2a1a'},
        'tint': ['top', 'plume'],
        'metal': ['helmet', 'cuirass'],
        'desat': 0.5,
        'hair': 'short', 'beard': True, 'top': 'sleeved', 'cuirass': True, 'bottom': 'skirt', 'wraps': 'boots',
        'gear': [('kettle', {'brim': 0.05, 'comb': True, 'peaks': True}),
                 ('plume', {'base': (0.0, -0.04, 0.28), 'tip': (0.02, -0.16, 0.44), 'n': 4}),
                 ('trousers', {'baggy': 1.3, 'knee': False})],
        'weapon': 'sword', 'props': {'sword': ('rapier', {})},
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Scout': {
        'archetype': 'footman',
        'colors': {'skin': '#b07a52', 'hair': '#2a1e14', 'trousers': '#c0a878', 'belt': '#4a3020', 'boots': '#5a4028'},
        'tint': ['bottom', 'strap', 'armband'],
        'metal': [],
        'desat': 0.75,
        'build': 'muscular',
        'hair': 'none', 'beard': True, 'top': 'bare', 'bottom': 'loincloth', 'wraps': 'boots',
        'gear': ['ponytail', ('chest_strap', {'tint': True}), ('trousers', {'baggy': 1.0}), ('bands', {'where': ('arm',)})],
        'weapon': None, 'offhand': 'gourd',
        'props': {'gourd': ('gourd', {})},
        'stance': {'hand_l': (-0.38, 0.10, 0.80)},
    },
    'Chasquis Scout': {
        'archetype': 'footman',
        'colors': {'skin': '#a86c44', 'hair': '#1a1210', 'belt': '#e0b030', 'wood': '#6a4428'},
        'tint': ['bottom', 'feather', 'flap', 'armband'],
        'metal': [],
        'desat': 0.65,
        'build': 'muscular',
        'hair': 'short', 'top': 'bare', 'bottom': 'loincloth',
        'gear': ['inca_headdress', ('loin_flap', {'length': 0.26}), ('bands', {'where': ('knee', 'ankle', 'wrist')})],
        'weapon': 'club', 'props': {'club': ('star_mace', {})},
        'actions': {'ATTACK1': 'attack_lunge'},
    },
    'Enslaved Worker': {
        'archetype': 'footman',
        'colors': {'skin': '#c89068', 'hair': '#4a2e1c', 'top': '#a8ae88', 'bottom': '#98a07c', 'belt': '#4a3a28',
                   'sandal': '#3a2a1c'},
        'tint': ['strap'],
        'metal': [],
        'desat': 0.8,
        'build': 'lean',
        'hair': 'long', 'beard': True, 'top': 'tunic', 'bottom': 'kilt', 'sandals': True,
        'gear': [('chest_strap', {'tint': True}), 'shackles'],
        'weapon': 'shovel',
        'stance': {'hand_r': (0.30, 0.20, 0.86), 'w_main': (-180, 0, 0)},
        'actions': {'ATTACK1': 'attack_thrust'},
    },
    'Inquisitor': {
        'archetype': 'footman',
        'colors': {'skin': '#c89070', 'hood': '#4a4a4e', 'top': '#46464a', 'robe': '#424246', 'bottom': '#424246',
                   'sandal': '#2a2420'},
        'tint': ['belt', 'book'],
        'metal': [],
        'hair': 'none', 'top': 'long_sleeved', 'bottom': 'skirt', 'sandals': True,
        'lock_feet': ['ATTACK1', 'FIDGET', 'VICTORY', 'FORTIFY'],
        'gear': ['cowl', ('robe', {'length': 0.84, 'flare': 0.13}), ('trousers', {'mat': 'robe', 'baggy': 1.1}), 'sash_ends', 'cross', ('sleeves', {'color': '#46464a', 'mat': 'top',
                                                                                      'wide': 1.5})],
        'weapon': 'club', 'offhand': 'book',
        'props': {'club': ('torch', {}), 'book': ('book', {})},
        'stance': {'hand_r': (0.30, 0.18, 0.90), 'w_main': (-20, 0, 0), 'hand_l': (-0.18, 0.30, 1.05),
                   'w_off': (-60, 0, 30), 'elbow_l': (-0.7, -0.6, -0.3)},
        'actions': {'ATTACK1': 'attack_thrust'},
    },
}
