"""Leaders, kings, armies and special units (models/leaders.py 'royal' archetype).

'King' needs no entry: its INI points at the Leader Ancient Times flics
(..\\Leader Ancient Times\\...), which the game resolves to that folder's sheets.
"""

# Shared looks
SKIN = '#c8946a'
SKIN_DARK = '#8a5a3a'
TAN_ROBE = '#a08a6c'


def royal(**kw):
    d = {'archetype': 'royal'}
    d.update(kw)
    return d


# Arm poses (humanoid stance channels)
HIPS = {'hand_r': (0.25, 0.02, 1.0), 'elbow_r': (1.0, -0.3, 0.1), 'hand_l': (-0.25, 0.02, 1.0), 'elbow_l': (-1.0, -0.3, 0.1)}
HIP_L = {'hand_l': (-0.25, 0.02, 1.0), 'elbow_l': (-1.0, -0.3, 0.1)}
HIP_R = {'hand_r': (0.25, 0.02, 1.0), 'elbow_r': (1.0, -0.3, 0.1)}
CROSSED = {'hand_r': (-0.14, 0.24, 1.22), 'elbow_r': (0.6, -0.2, -0.8), 'hand_l': (0.14, 0.2, 1.17),
           'elbow_l': (-0.6, -0.2, -0.8)}
CLASPED = {'hand_r': (0.05, 0.25, 1.02), 'elbow_r': (0.8, -0.4, -0.4), 'hand_l': (-0.05, 0.25, 1.0),
           'elbow_l': (-0.8, -0.4, -0.4)}
BEHIND = {'hand_r': (0.05, -0.22, 1.0), 'elbow_r': (0.9, -0.2, -0.3), 'hand_l': (-0.05, -0.22, 1.0),
          'elbow_l': (-0.9, -0.2, -0.3)}
LAPEL_R = {'hand_r': (0.06, 0.22, 1.3), 'elbow_r': (0.8, -0.4, -0.5)}
FEMALE = {'bulk': 0.88}


def ankle_robe(mat='robe', hem=0.05, r=(0.25, 0.22), **kw):
    d = {'mat': mat, 'hem': hem, 'hem_r': r}
    d.update(kw)
    return d


UNITS = {
    # -------------------------------------------------------------- the era leaders
    'Leader Ancient Times': royal(
        colors={'skin': SKIN, 'hair': '#e8e4dc', 'robe': TAN_ROBE, 'top': TAN_ROBE, 'gown': '#dcd8cc',
                'belt': '#6a4a2e', 'sandal': '#5a3a22', 'wood': '#a08060'},
        tint=['trim', 'cuff'],
        hair='none', beard2='long', top='long_sleeved', sandals=True,
        front=[('gown', 18, -0.1, 0.30), ('trim', 5, -0.1, 0.30, 112, 0.034), ('trim', 5, -0.1, 0.30, 68, 0.034)],
        collar='broad', collar_mat='trim', collar_kw={'r0': 0.1, 'r1': 0.2, 'z': 0.3},
        sleeves='robe', sleeve_wide=0.03, sleeve_cuff='cuff',
        robe=[{'mat': 'gown', 'hem': 0.07, 'hem_r': (0.22, 0.2)},
              {'mat': 'robe', 'hem': 0.06, 'hem_r': (0.26, 0.23), 'top_r': (0.2, 0.15), 'open': 60, 'edge': 'trim', 'edge_deg': 14,
               'bands': [(0.86, 0.93, 'trim'), (0.96, 1.0, 'trim')]}],
        held_r='crook', held_r_kw={'r': 0.03, 'hook': 0.09},
        gesture='raise',
    ),

    # -------------------------------------------------------------- kings
    'King American': royal(   # Lincoln: top hat, black frock coat, chin beard
        colors={'skin': '#c89070', 'hair': '#241c16', 'top': '#2a2826', 'coat': '#2a2826', 'pants': '#1e1c1c',
                'shirt': '#e8e4dc', 'shoes': '#3a2418', 'hat': '#1a1a1c'},
        tint=['vest', 'hat_band'],
        hair='short', beard2='chin', top='long_sleeved',
        front=[('vest', 26, -0.1, 0.25), ('shirt', 10, 0.25, 0.33, 90, 0.034)],
        headgear=[('top_hat', {})], pants='pants', shoes='shoes', belt=None,
        robe={'mat': 'coat', 'hem': 0.42, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.25, 0.2), 'open': 70},
        stance=LAPEL_R, gesture='raise', gesture_hand='l', stately=True,
    ),
    'King Arab': royal(   # Abu Bakr: turban, long pale robe, sash, beard
        colors={'skin': '#b08866', 'hair': '#2a2018', 'top': '#d4c8ae', 'robe': '#d4c8ae', 'sandal': '#4a3622'},
        tint=['turban', 'trim', 'sash_m'],
        hair='short', beard=True, top='long_sleeved', sandals=True, sash='sash_m', belt=None,
        headgear=[('turban', {'m': 'turban'})],
        robe=ankle_robe(r=(0.25, 0.21), bands=[(0.93, 1.0, 'trim')]),
        sleeves='robe', sleeve_wide=0.02, sleeve_cuff='trim',
        stance=CLASPED,
    ),
    'King Austria': royal(   # Charles V: beret, fur-trimmed coat, hose, and his hound
        colors={'skin': '#d0a07a', 'hair': '#3a2616', 'coat': '#6a4a30', 'fur': '#e8dcc0',
                'hose': '#e4e0d4', 'shoes': '#2a2018', 'hat': '#1c1a1a', 'brocade': '#5a4636'},
        tint=['top'],
        hair='short', beard=True, top='long_sleeved', pants='hose', shoes='shoes', belt=None,
        headgear=[('beret', {'m': 'hat', 'feather': 'feather'})],
        robe={'mat': 'coat', 'hem': 0.5, 'top': 0.14, 'top_r': (0.22, 0.17), 'hem_r': (0.3, 0.26), 'open': 80,
              'edge': 'fur', 'edge_deg': 12},
        cape={'mat': 'brocade', 'hem': 0.5, 'width': 1.05},
        collar='fur', collar_mat='fur', shoulders='epaulettes', shoulder_mat='fur',
        companion='dog', companion_at=(-0.62, 0.12, 0.0, 0.0),
        stance={'hand_l': (-0.5, 0.3, 0.92), 'elbow_l': (-0.8, -0.5, -0.2)}, gesture='raise', gesture_hand='r',
        stately=True,
    ),
    'King Aztec': royal(   # Montezuma: feather crest, gold collar, arms crossed, cape
        colors={'skin': '#a07a58', 'hair': '#1a1410', 'bottom': '#4a8070', 'cape_in': '#9a3a2a',
                'sandal': '#5a3a22', 'feather_w': '#d8bc5a', 'plume_r': '#9a3a2a', 'plume_g': '#4a8070'},
        tint=['cape', 'plume_t', 'hband'],
        hair='short', top='bare', bottom='kilt', sandals=True,
        headgear=[('plume_crest', {'colors': ('plume_g', 'feather_w', 'plume_r', 'feather_w', 'plume_t'), 'n': 11, 'length': 0.3, 'lean': 28,
                                   'width': 0.08, 'spread': (-100, 100)})],
        collar='broad', collar_mat='gold',
        cape={'mat': 'cape', 'hem': 0.4, 'width': 0.85, 'bands': [(0.0, 0.25, 'gold'), (0.7, 1.0, 'cape_in')]},
        stance=CROSSED,
    ),
    'King Babylonian': royal(   # Hammurabi: tall polos cap, square beard, long robe, mantle
        colors={'skin': '#b08866', 'hair': '#2a1e14', 'top': '#bca068', 'robe': '#bca068', 'robe2': '#86704a',
                'sandal': '#4a3622'},
        tint=['cape', 'trim'],
        hair='short', beard2='square', top='sleeved', sandals=True, belt=None,
        headgear=[('tall_crown', {'m': 'gold', 'h': 0.17, 'flare': 1.08, 'band': 'robe2', 'top': 'flat'})],
        robe=ankle_robe(r=(0.24, 0.21), stripes=('robe2', 3, 1), bands=[(0.0, 0.06, 'gold'), (0.94, 1.0, 'trim')]),
        cape={'mat': 'cape', 'hem': 0.16, 'width': 0.72, 'edge': 'gold'},
        stance=HIPS,
    ),
    'King Byzantines': royal(   # Theodora: jeweled crown, pale gown, blue mantle, gold collar
        colors={'skin': '#d0aa8c', 'hair': '#2a1a10', 'top': '#e8e2cc', 'gown': '#e8e2cc', 'sandal': '#c8a040',
                'jewel_b': '#8a2a2a'},
        tint=['cape', 'trim'],
        hair='long', top='long_sleeved', sandals=True, belt=None, build=FEMALE,
        headgear=[('tall_crown', {'m': 'gold', 'h': 0.12, 'flare': 1.12, 'band': 'jewel_b', 'top': 'open'})],
        collar='broad', collar_mat='gold', collar_kw={'r1': 0.21}, front=[('gold', 12, -0.1, 0.27)],
        robe=ankle_robe('gown', hem=0.03, r=(0.22, 0.2), panel=('gold', 16), bands=[(0.94, 1.0, 'gold')]),
        cape={'mat': 'cape', 'hem': 0.12, 'width': 0.85, 'bands': [(0.85, 1.0, 'gold')]},
        stance=CLASPED, gesture='present',
    ),
    'King Carthaginian': royal(   # Hannibal: steel cuirass, gold pauldrons, eye patch, breeches
        colors={'skin': '#a88466', 'hair': '#241a12', 'cuirass': '#7a8088', 'pants': '#3e342c', 'top': '#4e443c',
                'boots': '#2e241c', 'belt': '#5a3e26', 'bottom': '#4e443c'},
        tint=['bracers', 'belt'],
        hair='none', top='sleeved', cuirass=True, pants='pants', wraps='boots', bottom='skirt', bracers=True,
        face=['eyepatch'], shoulders='pauldrons', shoulder_mat='gold',
        gesture='point',
    ),
    'King Celtic': royal(   # Brennus: long hair, moustache, checked tunic, a big sword over the shoulder
        colors={'skin': '#c4a07c', 'hair': '#3a2414', 'pants': '#4a5038', 'belt': '#4a3020', 'boots': '#3a2a1c',
                'leather': '#5a3a22', 'bottom': '#5e4a32', 'bracers': '#5a3a22'},
        tint=['top'],
        hair='long', beard2='big_mustache', top='tunic', bottom='skirt', pants='pants', wraps='boots', bracers=True,
        held_r='longsword', held_r_kw={'length': 1.0},
        stance={'hand_r': (0.26, 0.16, 1.32), 'w_main': (75, 0, 15), 'elbow_r': (0.8, -0.4, -0.6)},
        gesture='point',
    ),
    'King Chinese': royal(   # Mao: grey tunic suit, hands clasped
        colors={'skin': '#d0a07a', 'hair': '#141414', 'top': '#6a7480', 'suit': '#6a7480', 'pants': '#4e5664',
                'shoes': '#3a2418'},
        tint=['armband'],
        hair='short', top='long_sleeved', pants='pants', shoes='shoes', belt=None,
        robe={'mat': 'suit', 'hem': 0.68, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.22, 0.17), 'rings': 4},
        collar='high', collar_mat='suit', arm_bands='armband',
        stance=CLASPED, gesture='wave', gesture_hand='r', stately=True,
    ),
    'King Egyptian': royal(   # Cleopatra: nemes, gold collar, white striped dress, crook
        colors={'skin': '#a87048', 'hair': '#141010', 'top': '#f0ece0', 'dress': '#f0ece0', 'sandal': '#c8a040'},
        tint=['nemes_a', 'band', 'stripe'],
        hair='none', top='tunic', sandals=True, belt=None, build=FEMALE,
        headgear=[('nemes', {})], collar='broad', collar_mat='gold', collar_mat2='stripe',
        robe=ankle_robe('dress', hem=0.08, r=(0.2, 0.18), panel=('stripe', 14), bands=[(0.3, 0.36, 'stripe'), (0.6, 0.66, 'stripe')]),
        arm_bands='gold', held_r='flail',
        stance={'hand_r': (0.36, 0.2, 0.95), 'w_main': (-60, 0, -10), 'hand_l': (-0.26, 0.1, 1.02), 'elbow_l': (-1, -0.3, 0)},
        gesture='raise', gesture_hand='r', gesture_w=(-10, 0, 0),
    ),
    'King English': royal(   # Elizabeth: ruff, red hair, a bell-shaped gown in stripes, scepter
        colors={'skin': '#e4c8b4', 'hair': '#9a4a26', 'ruff': '#f0eee8', 'gown': '#8e7e5a'},
        tint=['top', 'gstripe'],
        hair='none', hairdo='hair_bun', top='long_sleeved', belt=None, build=FEMALE,
        headgear=[('crown', {'r': 0.08, 'h': 0.03, 'z': 0.24, 'spike': 0.05, 'points': 6})],
        collar='ruff', front=[('gold', 12, -0.1, 0.27)],
        robe=ankle_robe('gown', hem=0.03, r=(0.42, 0.4), flare_k=0.55, stripes=('gstripe', 4, 1), panel=('gold', 16),
                        bands=[(0.96, 1.0, 'gold')]),
        held_r='scepter', held_r_kw={'head': 'orb'}, sleeves='top', sleeve_cuff='gold',
        stance={'hand_l': (-0.2, 0.3, 1.08), 'elbow_l': (-0.8, -0.4, -0.4)}, gesture='present', gesture_hand='l',
    ),
    'King French': royal(   # Joan of Arc: plate armor, a blue surcoat and cape with a fleur-de-lis, sword
        colors={'skin': '#ecc0a0', 'hair': '#8a3a1c', 'cuirass': '#c0c4cc', 'armor': '#c0c4cc', 'top': '#c0c4cc',
                'boots': '#a8acb4', 'pants': '#a8acb4'},
        tint=['tabard', 'cape'],
        hair='short', top='long_sleeved', cuirass=True, pants='pants', wraps='greaves', belt=None,
        shoulders='pauldrons', shoulder_mat='armor', build=FEMALE,
        robe={'mat': 'tabard', 'hem': 0.52, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.26, 0.2), 'open': 140,
              'open_at': 0, 'rings': 5},
        cape={'mat': 'cape', 'hem': 0.4, 'width': 0.8, 'emblem': ('gold', (3, 6), 2)},
        held_r='longsword',
        stance={'hand_r': (0.3, 0.22, 0.98), 'w_main': (-150, 0, -30), 'hand_l': (0.12, 0.24, 1.0), 'elbow_l': (-0.8, -0.4, -0.4)},
        run='full',
        gesture='raise', gesture_hand='l',
    ),
    'King German': royal(   # Bismarck: pickelhaube, grey tunic, sash, epaulettes, jackboots
        colors={'skin': '#e0b494', 'hair': '#c8c0b0', 'top': '#8a9098', 'coat': '#8a9098', 'pants': '#1e1e22',
                'boots': '#141416', 'helmet': '#9aa0a8'},
        tint=['sash_m', 'cuff'],
        hair='short', beard2='big_mustache', top='long_sleeved', pants='pants', wraps='boots', belt=None, sash='sash_m',
        headgear=[('pickelhaube', {'m': 'helmet'})], shoulders='epaulettes', cuffs='cuff', collar='high', collar_mat='coat',
        robe={'mat': 'coat', 'hem': 0.62, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.24, 0.19), 'rings': 4},
        stance=HIP_L, gesture='point', gesture_hand='r', stately=True,
    ),
    'King Greek': royal(   # Alexander: a blue himation over a white chiton, headband
        colors={'skin': '#c4a490', 'hair': '#8a6040', 'top': '#e4e0d6', 'chiton': '#e4e0d6', 'sandal': '#6a4a2a',
                'gband': '#c8a850'},
        tint=['himation'],
        hair='short', top='strap', sandals=True, belt=None,
        headgear=[('headband', {'m': 'gband'})],
        robe=[ankle_robe('chiton', hem=0.1, r=(0.21, 0.19)),
              ankle_robe('himation', hem=0.14, r=(0.25, 0.22), open=70, open_at=30, top_r=(0.2, 0.15))],
        stance={'hand_r': (0.12, 0.24, 1.3), 'elbow_r': (0.8, -0.4, -0.5)}, gesture='raise', gesture_hand='r',
    ),
    'King Hatti': royal(   # Mursilis: gold circlet, beard, pale robe, blue mantle, red sash, gold axe
        colors={'skin': '#b08a68', 'hair': '#2a1e14', 'top': '#d4c8a4', 'robe': '#d4c8a4', 'redsash': '#7a3226',
                'sandal': '#4a3622'},
        tint=['mantle', 'trim'],
        hair='short', beard2='square', top='sleeved', sandals=True, belt=None,
        headgear=[('circlet', {})], sleeves='top', sleeve_cuff='trim',
        robe=ankle_robe(r=(0.24, 0.21), panel=('redsash', 22), bands=[(0.0, 0.07, 'gold'), (0.9, 1.0, 'trim')]),
        cape={'mat': 'robe', 'hem': 0.1, 'width': 0.95},
        held_r='axe_gold', held_r_kw={'length': 0.55},
        stance={'hand_l': (-0.2, 0.28, 1.08), 'elbow_l': (-0.8, -0.4, -0.4)},
        gesture='raise', gesture_hand='r', gesture_w=(0, 0, 0),
    ),
    'King Incan': royal(   # Pachacuti: gold headdress, checked tunic, long cape, feather standard
        colors={'skin': '#9a7458', 'hair': '#141010', 'sandal': '#b89a50', 'top': '#8a6a3a', 'tunic': '#b0904a',
                'check': '#6a4e2a', 'plume_r': '#9a3a2a'},
        tint=['cape', 'plume_b'],
        hair='short', top='sleeved', sandals=True, belt=None, bracers=False,
        headgear=[('tall_crown', {'m': 'gold', 'h': 0.08, 'flare': 1.3, 'top': 'open'}),
                  ('feather_ring', {'n': 7, 'mats_cycle': ('plume_r', 'gold'), 'r': 0.1, 'z': 0.26, 'length': 0.12,
                                    'spread': (-50, 50), 'tilt': -30})],
        robe=ankle_robe('tunic', hem=0.42, r=(0.25, 0.21), stripes=('check', 2, 1), panel=('gold', 30),
                        bands=[(0.85, 1.0, 'gold')], rings=6),
        cape={'mat': 'cape', 'hem': 0.1, 'width': 0.95, 'bands': [(0.7, 0.8, 'gold')]},
        collar='broad', collar_mat='gold',
        held_l='feather_standard',
        gesture='raise', gesture_hand='r',
    ),
    'King Indian': royal(   # Gandhi: bald, glasses, white dhoti and shawl, long walking stick
        colors={'skin': '#8e6a50', 'top': '#e4e2dc', 'dhoti': '#e4e2dc', 'sandal': '#5a3a22', 'glasses': '#3a3a3a'},
        tint=['sash_w'],
        hair='none', top='sleeved', sandals=True, belt=None, build={'bulk': 0.85},
        face=['glasses'],
        robe=ankle_robe('dhoti', hem=0.36, r=(0.21, 0.18), rings=5),
        extras=[('chest', 'sash_band', {'rx': 0.3, 'ry': 0.16, 'width': 0.13, 'tilt': -40}, [])],
        held_l='walking_stick',
        gesture='raise', gesture_hand='r',
    ),
    'King Iroquois': royal(   # Hiawatha: great feather bonnet, bare chest, sash, leggings, feathered spear
        colors={'skin': '#a08066', 'hair': '#141010', 'pants': '#5e4632', 'feather': '#e8e4da', 'feather_o': '#a8582e',
                'sandal': '#5a3a22', 'belt': '#5a3a22'},
        tint=['feather_t', 'hband', 'loin', 'sash_m'],
        hair='long', top='bare', pants='pants', sandals=True, sash='sash_m',
        headgear=[('war_bonnet', {})],
        robe={'mat': 'loin', 'hem': 0.5, 'top': 0.11, 'top_r': (0.2, 0.15), 'hem_r': (0.2, 0.15), 'open': 220,
              'open_at': 0, 'rings': 4},
        held_r='spear_feathered', stance=HIP_L, gesture='point', gesture_hand='l',
    ),
    'King Japanese': royal(   # Tokugawa: eboshi cap, kimono with stiff shoulder wings, hakama
        colors={'skin': '#d8b088', 'hair': '#141010', 'hakama': '#6a6a70', 'collar_w': '#ece8e0', 'shoes': '#e8e4dc'},
        tint=['top', 'kata'],
        hair='short', top='long_sleeved', belt=None, shoes='shoes',
        headgear=[('eboshi', {})],
        front=[('collar_w', 8, 0.18, 0.33)],
        sleeves='top', sleeve_wide=0.05,
        extras=[('chest', 'kataginu', {}, [])],
        robe=ankle_robe('hakama', hem=0.03, r=(0.27, 0.2), stripes=('gold', 13, 1), bands=[(0.94, 1.0, 'gold')]),
        stance=HIPS, gesture='point', gesture_hand='r', stately=True,
    ),
    'King Korean': royal(   # Wang Kon: shaven head with a topknot, long pale robe in stripes
        colors={'skin': '#ccac90', 'hair': '#141010', 'top': '#bca474', 'robe': '#bca474', 'shoes': '#3a2a1e'},
        tint=['stripe'],
        hair='none', top='long_sleeved', belt=None, shoes='shoes',
        extras=[('head', 'topknot', {}, [('scale', 1.12)])],
        sleeves='top', sleeve_wide=0.04, sleeve_cuff='stripe',
        front=[('stripe', 10, -0.1, 0.33)],
        robe=ankle_robe(hem=0.03, r=(0.25, 0.22), stripes=('stripe', 6, 1), panel=('stripe', 10)),
        stance=CLASPED, gesture='raise', gesture_hand='r',
    ),
    'King Mayan': royal(   # Smoke-Jaguar: towering plumes, gold jewelry, jaguar-skin kilt, cape
        colors={'skin': '#9a7458', 'hair': '#141010', 'jaguar': '#c09450', 'spots': '#4a3018', 'sandal': '#5a3a22',
                'plume_w': '#e8e4da', 'plume_g': '#4a7a5e', 'hband': '#c8a850'},
        tint=['cape', 'plume_t'],
        hair='short', top='bare', sandals=True, belt=None,
        headgear=[('plume_crest', {'colors': ('plume_g', 'plume_t', 'plume_g', 'plume_w'), 'n': 11, 'length': 0.42, 'lean': 22,
                                   'width': 0.09, 'spread': (-95, 95)}),
                  ('feather_ring', {'n': 7, 'mats_cycle': ('plume_w',), 'r': 0.1, 'z': 0.26, 'length': 0.8,
                                    'spread': (-35, 35), 'tilt': 150, 'width': 0.07})],
        collar='broad', collar_mat='gold', arm_bands='gold',
        robe=ankle_robe('jaguar', hem=0.45, r=(0.23, 0.19), rings=5, stripes=('spots', 3, 1)),
        cape={'mat': 'cape', 'hem': 0.25, 'width': 0.78},
        stance=CROSSED,
    ),
    'King Mongol': royal(   # Temujin: fur hat, long golden deel, sash, boots, saber
        colors={'skin': '#c89468', 'hair': '#241a12', 'top': '#c09040', 'deel': '#c09040', 'boots': '#3a2a1e',
                'fur': '#5a4a3a'},
        tint=['hat_top', 'trim', 'sash2'],
        hair='short', beard2='goatee', top='long_sleeved', wraps='boots', belt=None,
        headgear=[('fur_hat', {})], sleeve_cuff='trim', sleeves='top',
        robe=ankle_robe('deel', hem=0.22, r=(0.27, 0.23), bands=[(0.0, 0.08, 'sash2'), (0.93, 1.0, 'trim')], panel=('trim', 6)),
        held_r='scimitar', gesture='point', gesture_hand='l', stately=True,
    ),
    'King Netherlands': royal(   # William: long curls, a vast blue cape spreading on the ground, cane
        colors={'skin': '#e8c0a0', 'hair': '#5a3a20', 'top': '#ece8e0', 'hose': '#ece8e0', 'shoes': '#1e1a18',
                'doublet': '#ece8e0'},
        tint=['cape', 'sash_m'],
        hair='none', hairdo='hair_long_curly', top='long_sleeved', pants='hose', shoes='shoes', belt=None, sash='sash_m',
        robe={'mat': 'doublet', 'hem': 0.6, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.25, 0.2), 'rings': 4},
        cape={'mat': 'cape', 'hem': 0.0, 'width': 1.25, 'train': 2.2, 'bands': [(0.9, 1.0, 'gold')], 'edge': 'gold'},
        held_r='cane', stately=True,
        stance={'hand_l': (-0.28, 0.18, 1.04), 'elbow_l': (-1.0, -0.3, 0.0)}, gesture='present', gesture_hand='l',
    ),
    'King Ottoman': royal(   # Osman: great turban, white kaftan, blue vest, moustache
        colors={'skin': '#d0a07a', 'hair': '#2a1e14', 'top': '#f0ece2', 'kaftan': '#f0ece2', 'turban': '#f4f2ea',
                'shoes': '#c8a040'},
        tint=['vest'],
        hair='short', beard2='big_mustache', top='long_sleeved', belt=None, shoes='shoes',
        headgear=[('turban', {'m': 'turban', 'big': 1.15, 'tall': 0.07, 'jewel': True, 'plume': 'plume_w'})],
        front=[('vest', 70, -0.1, 0.26)],
        robe=[ankle_robe('kaftan', hem=0.03, r=(0.24, 0.21)),
              ankle_robe('vest', hem=0.42, r=(0.26, 0.22), open=70, rings=5, top_r=(0.2, 0.15))],
        stance=CLASPED, gesture='raise', gesture_hand='r',
    ),
    'King Persian': royal(   # Xerxes: crenellated gold crown, curled beard, patterned tunic, leggings
        colors={'skin': '#b88c6c', 'hair': '#241a12', 'top': '#e8e4da', 'tunic': '#e8e4da', 'pants': '#6e5a46',
                'boots': '#5a3a22'},
        tint=['pattern'],
        hair='long', beard2='square', top='sleeved', pants='pants', wraps='boots', belt=None,
        headgear=[('crown', {'r': 0.11, 'h': 0.08, 'spike': 0.05, 'points': 6, 'jewels': None})],
        front=[('pattern', 22, 0.0, 0.25)], arm_bands='gold',
        robe=ankle_robe('tunic', hem=0.5, r=(0.24, 0.2), rings=5, panel=('pattern', 18), bands=[(0.86, 1.0, 'pattern')]),
        gesture='raise', gesture_hand='r',
    ),
    'King Portugal': royal(   # Henry the Navigator: chaperon hat, patterned doublet, hose, sword
        colors={'skin': '#d8b49a', 'hair': '#3a2a1c', 'hose': '#8a8a90', 'shoes': '#1e1a18', 'hat': '#1e1a18',
                'top': '#3e3428', 'doublet': '#3e3428'},
        tint=['dstripe'],
        hair='short', top='long_sleeved', pants='hose', shoes='shoes', belt=None,
        headgear=[('chaperon', {})], shoulders='epaulettes', cuffs='gold',
        robe={'mat': 'doublet', 'hem': 0.6, 'top': 0.14, 'top_r': (0.21, 0.16), 'hem_r': (0.27, 0.22), 'rings': 4,
              'stripes': ('dstripe', 3, 2), 'bands': [(0.0, 0.12, 'gold'), (0.88, 1.0, 'gold')]},
        held_r='longsword', held_r_kw={'length': 0.8},
        stance=dict(HIP_L, w_main=(-170, 0, -20)), gesture='point', gesture_hand='l',
    ),
    'King Roman': royal(   # Caesar: gold cuirass, white tunic, a cape over the shoulder, eagle staff
        colors={'skin': '#d8a880', 'hair': '#3a2a1c', 'cuirass': '#d0a848', 'top': '#f0ece2', 'tunic': '#f0ece2',
                'boots': '#6a4a2a'},
        tint=['cape'],
        hair='short', top='sleeved', cuirass=True, wraps='boots', belt=None,
        robe=ankle_robe('tunic', hem=0.52, r=(0.23, 0.2), rings=4, stripes=('gold', 4, 1)),
        cape={'mat': 'cape', 'hem': 0.34, 'width': 0.8, 'wrap': 28},
        held_r='tall_scepter', held_r_kw={'head': 'eagle'},
        gesture='raise', gesture_hand='r', gesture_w=(0, 0, 0),
    ),
    'King Russian': royal(   # Catherine: crown, a vast bell gown, orb and scepter
        colors={'skin': '#e4c8b4', 'hair': '#c8b8a0', 'top': '#b8bcc4', 'lace': '#e8e8e8', 'gown': '#9aa0aa'},
        tint=['sash_m', 'gstripe'],
        hair='none', hairdo='hair_bun', top='long_sleeved', belt=None, build=FEMALE, sash='sash_m',
        headgear=[('crown', {'r': 0.08, 'h': 0.06, 'z': 0.22, 'spike': 0.04, 'points': 8, 'arches': True})],
        front=[('lace', 16, -0.1, 0.25)], sleeves='top', sleeve_cuff='lace',
        robe=ankle_robe('gown', hem=0.02, r=(0.6, 0.56), flare_k=0.45, panel=('lace', 18), stripes=('gstripe', 4, 2),
                        bands=[(0.92, 1.0, 'lace')]),
        held_r='scepter', held_r_kw={'head': 'fleur'}, held_l='orb',
        stance={'hand_l': (-0.36, 0.26, 1.15), 'hand_r': (0.34, 0.24, 1.25), 'w_main': (-10, 10, 0)},
        gesture='present', gesture_hand='r',
    ),
    'King Spanish': royal(   # Isabella: crown and veil, blue gown with gold, a train around her feet
        colors={'skin': '#e4c8b4', 'hair': '#8a5a2a', 'veil': '#e8e8e8', 'lace': '#d8d8dc'},
        tint=['top', 'gown'],
        hair='long', top='long_sleeved', belt=None, build=FEMALE,
        headgear=[('crown', {'r': 0.11, 'h': 0.05, 'spike': 0.05, 'points': 7}), ('veil', {'length': 0.95})],
        cape={'mat': 'veil', 'hem': 0.55, 'width': 1.1},
        robe=ankle_robe('gown', hem=0.0, r=(0.42, 0.42), flare_k=1.8, train=0.5, stripes=('gold', 9, 1),
                        panel=('lace', 52), bands=[(0.94, 1.0, 'gold')]),
        held_r='scepter', held_r_kw={'head': 'fleur'},
        stance={'hand_l': (-0.2, 0.28, 1.08), 'elbow_l': (-0.8, -0.4, -0.4)}, gesture='present', gesture_hand='l',
    ),
    'King Sumeria': royal(   # Gilgamesh: tall white crown, square beard, bare arms, long banded skirt
        colors={'skin': '#a07a5c', 'hair': '#141010', 'crown_w': '#e4dccc', 'redband': '#8a3226', 'sandal': '#4a3622',
                'skirt': '#5a3a24', 'top': '#5a3a24'},
        tint=['sband'],
        hair='long', beard2='square', top='strap', sandals=True, belt=None, bracers=False,
        headgear=[('tall_crown', {'m': 'crown_w', 'h': 0.22, 'flare': 0.85, 'band': 'gold'})],
        collar='broad', collar_mat='gold', arm_bands='gold',
        robe=ankle_robe('skirt', hem=0.06, r=(0.25, 0.22), panel=('sband', 14),
                        bands=[(0.0, 0.08, 'redband'), (0.3, 0.38, 'sband'), (0.6, 0.68, 'sband'), (0.82, 0.88, 'gold'),
                               (0.88, 0.94, 'redband'), (0.94, 1.0, 'gold')]),
        held_r='tall_scepter', held_r_kw={'head': 'mace'},
        gesture='raise', gesture_hand='l',
    ),
    'King Viking': royal(   # Ragnar: helmet, beard, mail shirt, gold belt, long cape, sword
        colors={'skin': '#d8b49a', 'hair': '#b08048', 'mail': '#7e8288', 'top': '#7e8288', 'pants': '#5a4630',
                'boots': '#3a2a1c', 'helm': '#9a9ca0'},
        tint=['cape'],
        hair='long', beard=True, top='long_sleeved', pants='pants', wraps='boots', belt=None,
        headgear=[('helmet_round', {'m': 'helm'})],
        robe={'mat': 'mail', 'hem': 0.48, 'top': 0.12, 'top_r': (0.2, 0.15), 'hem_r': (0.26, 0.21), 'rings': 5,
              'bands': [(0.0, 0.1, 'gold')]},
        cape={'mat': 'cape', 'hem': 0.12, 'width': 0.95},
        held_r='longsword', held_r_kw={'length': 0.8},
        stance={'w_main': (-160, 0, -10)}, gesture='raise', gesture_hand='l',
    ),
    'King Zulu': royal(   # Shaka: plumed headdress, fur cape and kilt, cowhide shield, spear
        colors={'skin': '#5a3e2a', 'hair': '#141010', 'furc': '#a88a5c', 'top': '#a88a5c', 'sandal': '#3a2a1c',
                'fur': '#c4ac78', 'zfeather': '#d8c894', 'zfeather2': '#ece4cc', 'bands': '#6a5032'},
        tint=['hide'],
        hair='short', top='bare', belt=None, bracers=False, collar='fur', collar_mat='fur',
        headgear=[('zulu_headdress', {'length': 0.16, 'mane': 0.26, 'tilt': 4})], arm_bands='furc',
        robe=ankle_robe('furc', hem=0.45, r=(0.25, 0.22), rings=4, stripes=('bands', 5, 1)),
        extras=[('shin_r', 'fur_band', {}, []), ('shin_l', 'fur_band', {}, [])],
        held_r='iklwa', held_l='cowhide_shield', held_l_kw={'w': 0.47, 'h': 0.9},
        gesture='point', gesture_hand='r',
    ),
    'Leader Middle Ages': royal(   # a crowned knight: plate, a long cape with a lion, sword point down
        colors={'skin': '#e0b494', 'hair': '#5a3a20', 'armor': '#b8bcc4', 'cuirass': '#b8bcc4', 'top': '#b8bcc4',
                'pants': '#a8acb4', 'boots': '#9a9ea6', 'tabard': '#b09a6a', 'fur_w': '#f0f0ec'},
        tint=['cape'],
        hair='short', beard=True, top='long_sleeved', cuirass=True, pants='pants', wraps='greaves', belt=None,
        headgear=[('crown', {'r': 0.115, 'h': 0.05, 'spike': 0.05, 'points': 6})],
        shoulders='pauldrons', shoulder_mat='armor',
        robe={'mat': 'tabard', 'hem': 0.5, 'top': 0.12, 'top_r': (0.2, 0.15), 'hem_r': (0.25, 0.2), 'rings': 4,
              'open': 160, 'open_at': 270},
        cape={'mat': 'cape', 'hem': 0.04, 'width': 1.15, 'emblem': ('gold', (2, 6), 3),
              'bands': [(0.7, 0.78, 'gold'), (0.86, 1.0, 'fur_w')]},
        held_r='longsword', stance={'w_main': (-150, -10, -25), 'hand_r': (0.38, 0.22, 0.9)},
        gesture='raise', gesture_hand='r', gesture_w=(0, 0, 0), run='full',
    ),
    'Leader Industrial Ages': royal(   # a Napoleonic statesman: tailcoat, epaulettes, breeches, jackboots
        colors={'skin': '#e8c0a0', 'hair': '#e8e4dc', 'pants': '#9a9ca2', 'boots': '#18181a', 'waistcoat': '#ece8e0'},
        tint=['top', 'coat'],
        hair='none', hairdo='hair_queue', top='long_sleeved', pants='pants', wraps='boots', belt=None,
        shoulders='epaulettes', front=[('waistcoat', 36, -0.1, 0.3)], collar='high', collar_mat='gold', cuffs='gold',
        robe={'mat': 'coat', 'hem': 0.62, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.24, 0.2), 'open': 140,
              'rings': 5, 'edge': 'gold', 'edge_deg': 8},
        stance=LAPEL_R, gesture='point', gesture_hand='l', stately=True,
    ),
    'Leader Modern Times': royal(   # a modern officer: peaked cap, olive shirt, a wide sash, khakis, boots
        colors={'skin': '#c8a48a', 'hair': '#2a1e14', 'top': '#585c44', 'pants': '#9a907a', 'boots': '#4e3828',
                'cap': '#4a5038', 'cap_band': '#3a3a2a', 'stick': '#6a4a2a'},
        hair='short', beard2='goatee', top='sleeved', pants='pants', wraps='boots',
        headgear=[('peaked_cap', {})],
        tint=['sash_w'],
        extras=[('chest', 'sash_band', {'rx': 0.33, 'ry': 0.17, 'edge': 'gold', 'width': 0.12}, [])],
        held_r='walking_stick', held_r_kw={'length': 0.6, 'grip': 0.3},
        stance={'hand_r': (0.3, 0.28, 1.05), 'w_main': (-80, 0, 30)}, gesture='wave', gesture_hand='l', stately=True,
    ),
    'SciLeader': royal(   # Einstein: wild white hair, moustache, rumpled suit, cane and briefcase
        colors={'skin': '#e0b494', 'hair': '#e4e4e4', 'top': '#5a5a5e', 'jacket': '#5a5a5e', 'pants': '#3a3a3e',
                'shoes': '#2a2420'},
        tint=['tie'],
        hair='none', hairdo='hair_wild', beard2='big_mustache', top='long_sleeved', pants='pants', shoes='shoes',
        belt=None, front=[('tie', 8, -0.1, 0.3)],
        robe={'mat': 'jacket', 'hem': 0.6, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.24, 0.2), 'open': 40,
              'rings': 4},
        held_r='cane', held_l='briefcase',
        stance={'spine': (-6, 0, 0), 'head': (8, 0, 0)}, gesture='point', gesture_hand='r', stately=True,
    ),
    'Princess': royal(   # a princess: hair up, white gown with a blue and gold bodice, a wand
        colors={'skin': '#ecc8b0', 'hair': '#6a4224', 'gown': '#f4f2ec', 'top': '#f4f2ec'},
        tint=['bodice', 'gloves', 'hem'],
        hair='none', hairdo='hair_bun', top='tunic', belt=None, build=FEMALE,
        headgear=[('circlet', {'r': 0.1, 'z': 0.2})],
        front=[('bodice', 16, 0.0, 0.19), ('gold', 8, 0.0, 0.19, 90, 0.036)], sleeves='gloves',
        robe=ankle_robe('gown', hem=0.02, r=(0.32, 0.3), flare_k=1.0, panel=('gold', 10), bands=[(0.9, 1.0, 'hem')]),
        held_l='scepter', held_l_kw={'head': 'orb', 'length': 0.45},
        stance={'hand_l': (-0.32, 0.22, 1.32), 'w_off': (-10, 0, 0), 'elbow_l': (-1.0, -0.2, -0.3),
                'hand_r': (0.28, 0.14, 1.0), 'elbow_r': (1.0, -0.3, 0.0)},
        gesture='raise', gesture_hand='l', gesture_w=(0, 0, 0),
    ),
    'The King': royal(   # Elvis: pompadour, sunglasses, white jumpsuit, a high-collared cape spread wide
        colors={'skin': '#e8c0a0', 'hair': '#141418', 'top': '#f4f2ee', 'pants': '#f4f2ee', 'shoes': '#e8e4dc', 'cape_lining': '#f4f2ee'},
        tint=['cape', 'trim'],
        hair='none', hairdo='hair_pompadour', face=['sunglasses'], top='long_sleeved', pants='pants',
        pants_flare=0.06, shoes='shoes', belt=None,
        front=[('trim', 14, 0.05, 0.33)], collar='high', collar_mat='cape', cuffs='trim',
        cape={'mat': 'cape', 'hem': 0.8, 'width': 1.0, 'wrap': 25, 'edge': 'cape_lining'},
        stance={'hand_r': (0.62, 0.06, 1.0), 'elbow_r': (1.0, -0.3, -0.5), 'hand_l': (-0.62, 0.06, 1.0),
                'elbow_l': (-1.0, -0.3, -0.5), 'foot_r': (0.22, 0.04, 0.08), 'foot_l': (-0.22, -0.02, 0.08)},
        gesture='kneel',
    ),
    'Shogun': royal(   # a samurai lord: kabuto, a blue robe with wide sleeves, hakama, katana
        colors={'skin': '#c8a88c', 'hair': '#141010', 'hakama': '#3e3c40', 'top': '#4a4238', 'shoes': '#d8d4cc',
                'collar_w': '#e0dcd4', 'helm': '#34302c'},
        tint=['robe'],
        hair='short', top='long_sleeved', belt=None, shoes='shoes', cuirass=False,
        headgear=[('kabuto', {})], sleeves='robe', sleeve_wide=0.07, sleeve_cuff='gold',
        front=[('collar_w', 12, 0.1, 0.33), ('gold', 4, 0.1, 0.33, 104, 0.034), ('gold', 4, 0.1, 0.33, 76, 0.034)],
        extras=[('chest', 'kataginu', {'m': 'robe', 'width': 0.3}, [])],
        robe=[ankle_robe('hakama', hem=0.04, r=(0.26, 0.22), stripes=('gold', 9, 1)),
              ankle_robe('robe', hem=0.16, r=(0.29, 0.25), open=50, edge='gold', edge_deg=10,
                         bands=[(0.9, 1.0, 'gold')], top_r=(0.2, 0.15))],
        held_r='katana',
        stance={'hand_r': (0.3, 0.2, 1.2), 'w_main': (30, 0, 20), 'elbow_r': (0.8, -0.4, -0.5)},
        actions={'ATTACK1': 'attack_slash', 'ATTACK2': 'attack_chop', 'FORTIFY': 'fortify', 'VICTORY': 'victory'},
        gesture='point', gesture_hand='l',
    ),

    # -------------------------------------------------------------- armies: a standard bearer of the era
    'Army Ancient Times': royal(
        colors={'skin': SKIN, 'hair': '#4a2e1c', 'robe': TAN_ROBE, 'top': TAN_ROBE, 'gown': '#dcd8cc',
                'sandal': '#5a3a22'},
        tint=['trim', 'cuff'],
        hair='short', beard=True, top='long_sleeved', sandals=True,
        front=[('gown', 18, -0.1, 0.30), ('trim', 5, -0.1, 0.30, 112, 0.034), ('trim', 5, -0.1, 0.30, 68, 0.034)],
        sleeves='robe', sleeve_wide=0.03, sleeve_cuff='cuff',
        robe=[{'mat': 'gown', 'hem': 0.07, 'hem_r': (0.22, 0.2)},
              {'mat': 'robe', 'hem': 0.06, 'hem_r': (0.26, 0.23), 'top_r': (0.2, 0.15), 'open': 60, 'edge': 'trim',
               'edge_deg': 14, 'bands': [(0.9, 1.0, 'trim')]}],
        held_r='banner', held_r_kw={'kind': 'ancient', 'length': 2.6},
        actions={'DEATH': 'death_kneel'},
    ),
    'Army Middle Ages': royal(
        colors={'skin': '#d0b098', 'hair': '#3a2a1c', 'armor': '#b0b4bc', 'cuirass': '#b0b4bc', 'top': '#b0b4bc',
                'pants': '#a0a4ac', 'boots': '#92969e', 'tabard': '#7e7a72', 'fur_w': '#e8e8e4'},
        tint=['cape'],
        hair='short', beard=True, top='long_sleeved', cuirass=True, pants='pants', wraps='greaves', belt=None,
        shoulders='pauldrons', shoulder_mat='armor',
        robe={'mat': 'tabard', 'hem': 0.5, 'top': 0.12, 'top_r': (0.2, 0.15), 'hem_r': (0.25, 0.2), 'rings': 4,
              'open': 160, 'open_at': 270},
        cape={'mat': 'cape', 'hem': 0.04, 'width': 1.15, 'emblem': ('gold', (2, 6), 3),
              'bands': [(0.7, 0.78, 'gold'), (0.86, 1.0, 'fur_w')]},
        held_r='banner', held_r_kw={'kind': 'middle', 'length': 2.6}, run='full',
        actions={'DEATH': 'death_kneel'},
    ),
    'Army Industrial Ages': royal(
        colors={'skin': '#e8c0a0', 'hair': '#3a2a1c', 'pants': '#9a9ca2', 'boots': '#18181a', 'waistcoat': '#ece8e0',
                'hat': '#1e1e22'},
        tint=['top', 'coat'],
        hair='short', top='long_sleeved', pants='pants', wraps='boots', belt=None,
        headgear=[('bicorne', {})],
        shoulders='epaulettes', front=[('waistcoat', 22, -0.1, 0.3)], collar='high', collar_mat='coat', cuffs='gold',
        robe={'mat': 'coat', 'hem': 0.42, 'top': 0.14, 'top_r': (0.2, 0.15), 'hem_r': (0.24, 0.2), 'open': 110,
              'rings': 5, 'edge': 'gold', 'edge_deg': 8},
        held_r='banner', held_r_kw={'kind': 'industrial', 'length': 2.6},
        actions={'DEATH': 'death_kneel'},
    ),
    'Army Modern Times': royal(
        colors={'skin': '#d8a880', 'hair': '#2a1e14', 'top': '#5a6040', 'pants': '#a89a78', 'boots': '#5a3a22',
                'cap': '#4a5236', 'cap_band': '#3a3a2a'},
        tint=['sash_w'],
        hair='short', top='sleeved', pants='pants', wraps='boots',
        headgear=[('peaked_cap', {})],
        extras=[('chest', 'sash_band', {'rx': 0.33, 'ry': 0.17, 'edge': 'gold', 'width': 0.12}, [])],
        held_r='banner', held_r_kw={'kind': 'modern', 'length': 2.6},
        actions={'DEATH': 'death_kneel'},
    ),

    # -------------------------------------------------------------- the Holy Relic
    'Holy Relic': {'archetype': 'relic', 'anchor': (120.0, 126.0), 'scale': 0.92},
}
