"""Siege engines, guns, armor, aircraft and missiles (models/vehicles.py,
models/siege.py, models/aircraft.py, models/missiles.py)."""

UNITS = {
    'Catapult': {
        'archetype': 'catapult', 'fire': 0.37, 'size': 1.06,
        'tint': ['beam'],
        'crew': {'colors': {'skin': '#c8905c', 'hair': '#3a2616', 'bottom': '#6a4a2e', 'belt': '#4a3020',
                            'helmet': '#9a9aa0', 'boots': '#5a3e26'},
                 'tint': ['top'], 'hair': 'short', 'helmet': 'cap', 'top': 'sleeved', 'bottom': 'skirt',
                 'wraps': 'boots', 'metal': ['helmet']},
    },
    'Trebuchet': {
        'archetype': 'trebuchet', 'fire': 0.24,
        'tint': ['band'],
        'crew': {'colors': {'skin': '#c8905c', 'hair': '#3a2616', 'belt': '#3a2a1c', 'boots': '#4a3424'},
                 'tint': ['top', 'bottom'], 'hair': 'short', 'top': 'sleeved', 'bottom': 'long',
                 'wraps': 'boots', 'hat': ('cap', '#6a5a44')},
    },
    'Hwacha': {
        'archetype': 'hwacha',
        'tint': ['rail'],
        'crew': {'colors': {'skin': '#d0a070', 'hair': '#2a2018', 'top': '#9aa2b0', 'bottom': '#9aa2b0',
                            'belt': '#ffffff', 'boots': '#3a3430', 'bracers': '#8a8e96'},
                 'tint': ['belt'], 'hair': 'short', 'top': 'sleeved', 'bottom': 'long',
                 'wraps': 'boots', 'bracers': True, 'hat': ('gat', '#c8a868', '#5a4a30')},
    },
    'Cannon': {
        'archetype': 'cannon',
        'tint': ['wheel'],
        'colors': {'carriage': '#3e4044', 'carriage_dark': '#28292c'},
        'crew': {'colors': {'skin': '#d8a478', 'hair': '#3a2a1c', 'bottom': '#ece8de', 'belt': '#f0eee8',
                            'boots': '#1e1e20', 'wood': '#6a4a2e'},
                 'tint': ['top'], 'hair': 'short', 'top': 'sleeved', 'bottom': 'long', 'wraps': 'boots',
                 'hat': ('shako', '#1e1e22', '#f4f4f0')},
    },
    'Artillery': {
        'archetype': 'fieldgun',
        'tint': ['spade', 'shield_top'],
        'colors': {'paint': '#5a5e50', 'paint_dark': '#3a3d32', 'rim': ('#44483a', 0.3, 16)},
    },
    'Flak': {
        'archetype': 'flak',
        'tint': ['hub', 'band'],
        'colors': {'paint': '#5e5d52', 'paint_dark': '#3a3a33', 'shield': '#4c4b43', 'mag': '#76756a'},
        'crew': {'colors': {'skin': '#d0a078', 'hair': '#3a2a1c', 'top': '#5a6050', 'bottom': '#5a6050',
                            'belt': '#2a2a24', 'boots': '#26241f', 'bracers': '#ffffff'},
                 'tint': ['bracers'], 'hair': 'short', 'top': 'sleeved', 'bottom': 'long', 'wraps': 'boots',
                 'bracers': True, 'hat': ('steel', '#4e5444')},
    },
    'Tank': {
        'archetype': 'armor', 'model': 'sherman',
        'tint': ['band', 'decal'],
    },
    'Panzer': {
        'archetype': 'armor', 'model': 'panzer', 'turret_off': True,
        'colors': {'paint': '#a6aa8c', 'paint_dark': '#6e7662'},
        'tint': ['decal'],
    },
    'Modern Armor': {
        'archetype': 'armor', 'model': 'abrams',
        'colors': {'paint': '#a29478', 'paint_dark': '#6a604e'},
        'tint': ['decal'],
    },
    'Mech Infantry': {
        'archetype': 'armor', 'model': 'bradley',
        'colors': {'paint': '#aaa08c', 'paint_dark': '#746c5e', 'paint_brown': '#58524a'},
        'tint': ['decal'],
    },
    'Radar Artillery': {
        'archetype': 'armor', 'model': 'mlrs',
        'tint': ['decal'],
    },
    'Mobile SAM': {
        'archetype': 'armor', 'model': 'sam',
        'colors': {'paint': '#6a6858', 'paint_dark': '#4a483e'},
        'tint': ['decal'],
    },
    'Fighter': {'archetype': 'aircraft', 'model': 'fighter', 'tint': ['band'], 'weapon': 'guns', 'size': 0.85},
    'Jet Fighter': {'archetype': 'aircraft', 'model': 'mig', 'tint': ['band'], 'weapon': 'missile'},
    'F-15': {'archetype': 'aircraft', 'model': 'f15', 'tint': ['band'], 'weapon': 'missile'},
    'Stealth Fighter': {'archetype': 'aircraft', 'model': 'f117', 'tint': ['band'], 'weapon': 'missile'},
    'Bomber': {'archetype': 'aircraft', 'model': 'b17', 'tint': ['band'], 'weapon': 'guns'},
    'Stealth Bomber': {'archetype': 'aircraft', 'model': 'b2', 'tint': ['band'],
                       'colors': {'paint': '#56575a', 'paint_dark': '#444547'}, 'weapon': 'guns'},
    'Helicopter': {'archetype': 'aircraft', 'model': 'chinook', 'tint': ['band'], 'weapon': 'guns'},
    'Cruise Missile': {'archetype': 'cruise_missile', 'tint': ['band']},
    'ICBM': {'archetype': 'rocket', 'tint': ['band'], 'length': 8.0, 'radius': 0.55, 'stages': 3},
    'Tactical Nuke': {'archetype': 'rocket', 'tint': ['band'], 'length': 7.0, 'radius': 0.5, 'stages': 2},
}
